### ISSUE TITLE
Integration with android in AndroidStudio

### ISSUE THREAD

**Issue by gouravkundu** [hosopy/actioncable-client-java#1]
Not able to import as a gradle module in existing android project. it will be very kind of you if 
you provide any solution

**Comment by tpmullan** [comment]
I gave a simple example of how to integrate with android studio in my pull request.  It would probably be best to edit the values to point at this repo but I needed it to work immediately for my project.

**Comment by hosopy** [comment]
@tpmullan Thank you!
