### ISSUE TITLE
Message {"type":"welcome"}

### ISSUE THREAD

**Issue by hosopy** [hosopy/actioncable-client-java#14]
I found WebSocketListener receives a message `{"type":"welcome"}` before receiving `{"type":"confirm_subscription"}`.

According to the actioncable(5.1.4) implementation, the message `{"type":"welcome"}` should work as an alternative of `WebSocketListener#onOpen`

https://github.com/rails/rails/blob/v5.1.4/actioncable/app/assets/javascripts/action_cable/connection.coffee#L88

```coffee
  events:
    message: (event) ->
      return unless @isProtocolSupported()
      {identifier, message, type} = JSON.parse(event.data)
      switch type
        when message_types.welcome
          @monitor.recordConnect()
          @subscriptions.reload()
        when message_types.ping
          @monitor.recordPing()
        when message_types.confirmation
          @subscriptions.notify(identifier, "connected")
        when message_types.rejection
          @subscriptions.reject(identifier)
        else
          @subscriptions.notify(identifier, "received", message)
```

**Comment by shobhitic** [comment]
Can I take this up?

**Comment by hosopy** [comment]
@shobhitic Thank you! Please send pull request when it is ready.

**Comment by shobhitic** [comment]
Please review. Very small changes - https://github.com/hosopy/actioncable-client-java/pull/17
