### ISSUE TITLE
Upgrade of okhttp-ws from 2.X to 3.X

### ISSUE THREAD

**Issue by hosopy** [hosopy/actioncable-client-java#16]
The latest version of OkHttp is 3.9.0.
After #15, Try to upgrade to 3.X and test.

* OkHttp 3.X includes okhttp-ws in itself.
* Change Log: https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-300

**Comment by h0jeZvgoxFepBQ2C** [comment]
Someone already made a PR for OkHttp 3: #29 - Could you merge it? Or is this repo not maintained anymore?

**Comment by h0jeZvgoxFepBQ2C** [comment]
I've released a RC for 3.12.1, see here: https://github.com/hosopy/actioncable-client-java/releases/tag/0.2.RC1
