### ISSUE TITLE
java.lang.NoClassDefFoundError: com.hosopy.actioncable.Connection$4

### ISSUE THREAD

**Issue by naumanmir** [hosopy/actioncable-client-java#20]
Consumer consumer = ActionCable.createConsumer(uri);
error is coming at this line. Please help.

**Comment by fraz017** [comment]
Having the same issue. Any help please!

**Comment by h0jeZvgoxFepBQ2C** [comment]
@naumanmir Could you provide a full example?
Which version are you using?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Stale. Please submit a new ticket if this is still open.
