### ISSUE TITLE
How can i set client origin.

### ISSUE THREAD

**Issue by nomanbiniqbal** [hosopy/actioncable-client-java#21]
I m not able to connect with server due to access origin is not present in request. 
this lib provide to set origin 
[https://github.com/danielrhodes/Swift-ActionCableClient](url)
is there any option to set origin

**Comment by MSchmidt** [comment]
Just add your Origin as Header:

```java
headers.put("Origin", "https://your-origin.tdl");
```

**Comment by flyfy1** [comment]
thanks, that's really helpful

**Comment by fabiantorresm** [comment]
Hola, me pueden ayudar?
Resulta que si hago todo lo de la documentación y si puedo obtener datos, pero no puedo enviar datos usando @perform, con esto queda solucionado o tengo algo que hacer en mi server rails 5?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Please open a new issue for this @fabiantorresm if your problem is still persisting, the current issue will be marked as fixed when I push my recent git commits.
