### ISSUE TITLE
Remove action property from command data

### ISSUE THREAD

**Issue by MSchmidt** [hosopy/actioncable-client-java#22]
https://github.com/hosopy/actioncable-client-java/blob/dfb21b887ffef28cd5f2c93311e2baa6d25c0750/src/main/java/com/hosopy/actioncable/SubscriptionProxy.java#L70

The TODO is already there. This line causes issues in Rails because most models don't have an action attribute. Why was this added in the first place?

**Comment by hosopy** [comment]
Set milestone `0.1.3`

**Comment by h0jeZvgoxFepBQ2C** [comment]
Actually as far as I understand the ActionCable protocol, there is always a "action" property included?

See also https://github.com/NullVoxPopuli/action_cable_client#the-action-cable-protocol
