### ISSUE TITLE
Actioncable not working with build release.

### ISSUE THREAD

**Issue by loctra** [hosopy/actioncable-client-java#23]
App working with build variant debug very good but when i changed into build varian release it not working.

**Comment by cuongmanhvo162** [comment]
I was release an app with using this library and got no issue. Could you please specific your issues in detail?

**Comment by loctra** [comment]
I has been changed release with 'debuggable true', it's okey but 'debuggable false' the call back Subscription did not return

**Comment by loctra** [comment]
@cuongmanhvo162 would you have better idea for config build.gradle relase? Thankyou so much your reply.

**Comment by cuongmanhvo162** [comment]
Hello there, 
My config file was merely simple and did not have any special customized. I using product flavor to specific the config for staging and prod build

`productFlavors {
        production {
            applicationId 'susu'
            buildConfigField('String', 'HOST', '"https://blahblah.com/api/v2/"')
            buildConfigField('String', 'WEB_SOCKET', '"wss://chat/cable"')
            targetSdkVersion 22
            buildConfigField("boolean", "CHECK_APP_VERSION", "true")
        }
        staging {
            applicationId 'susu'
            buildConfigField('String', 'HOST', '"https://www.staging.blahblah.com/api/v2/"')
            buildConfigField('String', 'WEB_SOCKET', '"wss://staging.chat/cable"')
            targetSdkVersion 22
            buildConfigField("boolean", "CHECK_APP_VERSION", "false")
        }
    }`

Make sure the uri is correct. Since the debuggable mode is only using to allow you to debug a release APK, I do not think it is the root cause.

Also, please check with the backend team, maybe the problem come from the prod server.

**Comment by loctra** [comment]
@cuongmanhvo162 I fixed.
adding more proguad-rule.pro 
> -keep class com.hosopy.actioncable.** { *; }
Thanks a lot your support :1st_place_medal:

**Comment by cuongmanhvo162** [comment]
Ah I see. the ProGuard just rip off actioncable library.

Thanks for your update.

**Comment by ViTVetal** [comment]
@cuongmanhvo162 a little off topic

Look like you use SSL (**wss**://chat/cable) in your project. Did you add some extra options? (like sslContext or hostnameVerifier) Did you try to use self-signed SSL certificate? 

With self-signed certificate I get in  onFailed() `javax.net.ssl.SSLHandshakeException: Handshake failed`
