### ISSUE TITLE
W/System.err: com.hosopy.actioncable.ActionCableException: java.io.EOFException

### ISSUE THREAD

**Issue by harshakuk** [hosopy/actioncable-client-java#27]
Its telling that the resource failed to call close and right after that am getting this exception, where can I exactly close the resource on android client side?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Could you try it again with the [latest RC](https://github.com/hosopy/actioncable-client-java/releases/tag/0.2.RC1)?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Stale, please comment and I will reopen it again.
