### ISSUE TITLE
Connection to action cable is failed every time. Guide me where i am wrong

### ISSUE THREAD

**Issue by noumanjamil16** [hosopy/actioncable-client-java#28]
URI uri = new URI("ws://94.177.249.182:3000/cable");
        Consumer consumer = ActionCable.createConsumer(uri);

// 2. Create subscription
        Channel appearanceChannel = new Channel("minutes");
        Subscription subscription = consumer.getSubscriptions().create(appearanceChannel);

        subscription
                .onConnected(new Subscription.ConnectedCallback() {
                    @Override
                    public void call() {
                        Log.e("Cable","Connected");
                        // Called when the subscription has been successfully completed
                    }
                }).onRejected(new Subscription.RejectedCallback() {
            @Override
            public void call() {
                // Called when the subscription is rejected by the server
                Log.e("Cable","Rejected");
            }
        }).onReceived(new Subscription.ReceivedCallback() {
            @Override
            public void call(JsonElement data) {
                // Called when the subscription receives data from the server
                Log.e("Data",data.getAsString());
            }
        }).onDisconnected(new Subscription.DisconnectedCallback() {
            @Override
            public void call() {
                // Called when the subscription has been closed
            }
        }).onFailed(new Subscription.FailedCallback() {
            @Override
            public void call(ActionCableException e) {
                // Called when the subscription encounters any error
                Log.e("Cable","Error occurred");
            }
        });

// 3. Establish connection
        consumer.connect();

**Comment by ViTVetal** [comment]
https://stackoverflow.com/a/47050965/3194048
