### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [hosopy/actioncable-client-java#31]
Hi,

since there are many forks out there already I would be happy to help to merge things together in this repo? (Upgrade to okhttp 3, add isConnected-method to Connection,...).

Would you be interested in another maintainer for your repo?

Please let me know, thank you!

**Comment by hosopy** [comment]
@h0jeZvgoxFepBQ2C Thank you for offering help. Recently I have no time to maintain this repo, so I'm grad to have collaborators. 

I have invited you as a collaborator and created milestones below.

* 0.1.3 (31 Mar 2019)
    * Small bugfix and enhancement
* 0.2.0 (31 Apr 2019)
    * Upgrade to okhttp 3
    * Other enhancement

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you very much, I'm happy to help out.

Is there any reason why dates are set for the releases?
If you don't mind I would release already a 2.0.RC1, since I need okhttp 3 in my own project?

**Comment by hosopy** [comment]
@h0jeZvgoxFepBQ2C OK. Dates of the milestones are temporary. The release of `2.0.RC1` is a good idea to test okhttp 3.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Great, released it some minutes ago 👍
