### ISSUE TITLE
consumer.disconnect() is not unsubscribing the subscriptions

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [hosopy/actioncable-client-java#32]
I just realized that ```consumer.disconnect()``` doesn't clear the subscriptions - and I receive onReceived-Callbacks, even after I told the consumer to disconnect.

We should remove all subscriptions on disconnect, or am I wrong @hosopy ?
I'm happy to provide a PR, if this is the case.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I've added a method called ```consumer.unsubscribeAndDisconnect()```, would be fine if someone could give feedback on this, see commit 69c519ed8c51d33f177f90441f897453978c1474 

After using this method, I also don't get the invalid/unrequested callback calls again.

**Comment by fabiantorresm** [comment]
> He agregado un método llamado `consumer.unsubscribeAndDisconnect()`, estaría bien si alguien pudiera dar su opinión sobre esto, vea cometer [69c519e](https://github.com/hosopy/actioncable-client-java/commit/69c519ed8c51d33f177f90441f897453978c1474)
> 
> Después de usar este método, tampoco recibo nuevamente las llamadas de devolución de llamada no válidas / no solicitadas. 
> Desafortunadamente mi examen está roto, no sé por qué en este momento ...


I tried this change and it did not work, update to version 0.2 and it does not recognize the method. Thank you.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Maybe you only tried the release 0.2.RC1 - the unsubscribeAndDisconnect() method was implemented later, I was just referring to the corresponding git commit.

But you can try the 0.2.RC2 release, which I published right now: https://github.com/hosopy/actioncable-client-java/releases/tag/0.2.RC2

If there is any isses, I will reopen this ticket again - right now it works pretty fine for my company in production.

**Comment by fabiantorresm** [comment]
Esta configuración es correcta?

public static void connectToActionCable() throws URISyntaxException {

        String domain = "192.168.0.103:3000";
        // 1. Setup
        URI uri = null;
        try {
            uri = new URI("ws://".concat(domain).concat("/cable"));
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

        Consumer.Options options = new Consumer.Options();
        options.reconnection = true;
        options.headers = new ArrayMap<>();
        options.headers.put("Origin", "http://".concat(domain));

        options.headers.put("Content-Type", "application/json");

        final Consumer consumer = ActionCable.createConsumer(uri, options);


        if (consumer.isConnected()){
            // 2. Create subscription
            Channel appearanceChannel = new Channel("BookChannel");
            final BookSubscription subscription = consumer.getSubscriptions().create(appearanceChannel, BookSubscription.class);
            Log.d("cableDebug", ""+subscription.getIdentifier().toString());
            subscription
                    .onConnected(new Subscription.ConnectedCallback() {
                        @Override
                        public void call() {
                            Log.d("cableDebug", "onConnected");
                            subscription.join();
                            subscription.sendMessage("fabiantorresm_01", true);
                            subscription.say_hi("fabiantorresm_02", true);
                        }
                    })
                    .onRejected(new Subscription.RejectedCallback() {
                        @Override
                        public void call() {
                            Log.d("cableDebug", "onRejected");
                            // Called when the subscription is rejected by the server
                        }
                    })
                    .onReceived(new Subscription.ReceivedCallback() {
                        @Override
                        public void call(JsonElement data) {
                            Gson gson = new Gson();
                            Log.d(TAG, "Datos recibidos: " + data);
                            //notification();
                        }
                    })
                    .onDisconnected(new Subscription.DisconnectedCallback() {
                        @Override
                        public void call() {
                            Log.d("cableDebug", "onDisconnected");
                            // Called when the subscription has been closed
                            consumer.unsubscribeAndDisconnect();
                        }
                    }).onFailed(new Subscription.FailedCallback() {
                @Override
                public void call(ActionCableException e) {
                    Log.d("cableDebug", "onFailed: " + e.getMessage());
                    e.printStackTrace();
                    // Called when the subscription encounters any error
                    consumer.unsubscribeAndDisconnect();
                }
            });
            // 3. Establish connection

            consumer.connect();
        }else{
            consumer.connect();
        }

**Comment by fabiantorresm** [comment]
Hi, sorry for the inconvenience.  Will you have an example of this code in production?  I am using evernote job Android for background work and every time this code is executed I create a new subscription.
