### ISSUE TITLE
Fix proguard rule in readme, please

### ISSUE THREAD

**Issue by maciekbaranowskiqq** [hosopy/actioncable-client-java#36]
`-keep class com.hosopy.actioncable.** { *; }`
`-keep interface com.hosopy.actioncable._* { *; }`

**Comment by h0jeZvgoxFepBQ2C** [comment]
Should both lines replace the current entries or should this be added additional?

**Comment by maciekbaranowskiqq** [comment]
Both lines should replace the current entries, thanks.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thanks four your report 👍
