### ISSUE TITLE
reconnection问题

### ISSUE THREAD

**Issue by tz-xiaomage** [hosopy/actioncable-client-java#4]
设置reconnection为true之后，就算socket连接成功了，也依旧是一直不停的重新连接

**Comment by hosopy** [comment]
After the connection is set to true, even if the socket connection is successful, it still has been kept to reconnect.

**Comment by shobhitic** [comment]
Hi, I'd like to help with this issue. How do I reproduce it?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Please open a new issue if this still occures in the [last RC](https://github.com/hosopy/actioncable-client-java/releases/tag/0.2.RC1)
