### ISSUE TITLE
Socket cloesd after some Seconds

### ISSUE THREAD

**Issue by samkazmi** [hosopy/actioncable-client-java#5]
why the socket is closing after some time?
How can i Ping pong the server so socket wont get closed
my code is below

```
String wsuri = "ws://52.37.206.155/cable?" + "email=" + Constants.EMAIL
                + "&sessionToken=" + Constants.SESSION_TOKEN
                + "&client=" + Constants.CLIENT;
        URI uri = null;
        try {
            uri = new URI(wsuri);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        Consumer.Options options = new Consumer.Options();
        options.reconnection = true;
        options.reconnectionMaxAttempts = 1000;
        options.reconnectionDelayMax = 10;
        consumer = ActionCable.createConsumer(uri, options);
        // 2. Create subscription
        Channel appearanceChannel = new Channel("ConversationsChannel");
        appearanceChannel.addParam("room", "conversations:" + conversation.getId());
        subscription = consumer.getSubscriptions().create(appearanceChannel);
        subscription
                .onConnected(new Subscription.ConnectedCallback() {
                    @Override
                    public void call() {
                        isConnected = true;
                        Log.v("onConnected", "subscription has been successfully completed");
                    }
                }).onRejected(new Subscription.RejectedCallback() {
            @Override
            public void call() {
                isConnected = false;
                Log.v("onRejected", "subscription is rejected by the server");
            }
        }).onReceived(new Subscription.ReceivedCallback() {
            @Override
            public void call(final JsonElement data) {
                Log.v("onReceived", "subscription receives data from the server " + data.toString());
            }
        }).onDisconnected(new Subscription.DisconnectedCallback() {
            @Override
            public void call() {
                // Called when the subscription has been closed
                Log.v("onDisconnected", "subscription has been closed");
            }
        }).onFailed(new Subscription.FailedCallback() {
            @Override
            public void call(final ActionCableException e) {
                isConnected = false;
                // Called when the subscription encounters any error
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        Toast.makeText(ConversationActivity.this, "Disconnected", Toast.LENGTH_SHORT).show();
                    }
                });
                Log.e("onFailed", "subscription encounters any error");
                e.printStackTrace();
            }
        });

        consumer.connect();
```

socket miss data while sending and receiving. due to socket closing after some seconds.

**Comment by macbury** [comment]
In final version of rails 5 they did change few things to make more consistient in communication. I have fixed this issue with this pull request: https://github.com/hosopy/actioncable-client-java/pull/6

**Comment by hosopy** [comment]
Merge #6 and tagged as 0.1.1

**Comment by samkazmi** [comment]
thanks for the replies
but i solved it by updating the okhttp library and ` options.reconnection = false;` if `reconnection` is `false` then it doesn't disconnects so i did this for reconnecting
` public void connect() {
        task = new TimerTask() {
            @Override
            public void run() {
                JsonObject jsonObject = new JsonObject();
                jsonObject.addProperty("channel", "ConversationsChannel");
                if (isConnected)
                    subscription.perform("subscribe", jsonObject);
            }
        };
        timer = new Timer();

        IntentFilter filter = new IntentFilter("com.pantera.thegrid.SOCKET_OPERATION");
        LocalBroadcastManager.getInstance(context).registerReceiver(receiver, filter);
        String wsuri = LINK + "email=" + Constants.EMAIL
                + "&sessionToken=" + Constants.SESSION_TOKEN
                + "&client=" + Constants.CLIENT;
        Log.v("connecting to", wsuri);
        URI uri = null;
        try {
            uri = new URI(wsuri);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        Consumer.Options options = new Consumer.Options();
        options.reconnection = false;
        options.reconnectionMaxAttempts = 5;
        options.reconnectionDelayMax = 1000 * 10;
        consumer = ActionCable.createConsumer(uri, options);
        Channel appearanceChannel = new Channel("ConversationsChannel");
        subscription = consumer.getSubscriptions().create(appearanceChannel);
        subscription
                .onConnected(new Subscription.ConnectedCallback() {
                    @Override
                    public void call() {
                        Log.v("onConnected", "subscription has been successfully completed");
                        isConnected = true;
                    }


                })
                .onRejected(new Subscription.RejectedCallback() {
                    @Override
                    public void call() {
                        Log.v("onRejected", "subscription is rejected by the server");
                        isConnected = false;
                    }
                })
                .onReceived(new Subscription.ReceivedCallback() {
                    @Override
                    public void call(final JsonElement data) {
                        Log.v("onReceived", "subscription receives data from the server " + data.toString());
                       
                    }

                })
                .onDisconnected(new Subscription.DisconnectedCallback() {
                    @Override
                    public void call() {
                        isConnected = false;
                  
                      //  disconnect();
                       // connect();
                    }
                })
                .onFailed(new Subscription.FailedCallback() {
                    @Override
                    public void call(final ActionCableException e) {
                        Log.e("onFailed", "subscription encounters any error " + e.toString());
                        isConnected = false;
                      //  disconnect();
                      //  connect();

                    }
                });

        consumer.connect();
        timer.schedule(task, 2000, 2000);
    }`
